### PR TITLE
Monero rpc installer for windows

### LINKED ISSUE #228: Add windows support to swap_cli
Only linux and Mac OS builds are currently supported for the swap cli because:

- [ ]  Monero installer does not support decoding of the downloaded Windows Monero cli package
- [ ] Feature gate tokio-tar because it doesn't build on windows
```
  Compiling tokio-tar v0.2.0 (D:\a\xmr-btc-swap\xmr-btc-swap\tokio-tar)
680
error[E0433]: failed to resolve: could not find `os` in `fs`
681
   --> tokio-tar\src\entry.rs:583:28
682
    |
683
583 |                 tokio::fs::os::windows::symlink_file(src, dst).await
684
    |                            ^^ could not find `os` in `fs`
685

686
error: aborting due to previous error
687

688
For more information about this error, try `rustc --explain E0433`.
689
error: could not compile `tokio-tar`
```

Address the above issue/s for windows support

### PR DESCRIPTION
**Pull request by rishflab**
I could not find an async zip archive extractor. The download is still async. One potential follow up could be to spawn the extraction of the zip in the windows path.

Closes #228

### CODE REVIEW

File: swap/src/bin/monero_wallet_rpc.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
+use anyhow::Result;
+use swap::monero;
+
+#[tokio::main]
+async fn main() -> Result<()> {
```
Comment (thomaseizinger) [inline swap/src/bin/monero_wallet_rpc.rs]: Did you intend to keep this long-term?

File: swap/src/monero/wallet_rpc.rs [hunk 2]
```diff
@@ -13,23 +12,28 @@ use tokio::{
...
 
 #[cfg(target_os = "linux")]
 const DOWNLOAD_URL: &str = "https://downloads.getmonero.org/cli/monero-linux-x64-v0.17.1.9.tar.bz2";
 
-#[cfg(not(any(target_os = "macos", target_os = "linux")))]
-compile_error!("unsupported operating system");
+#[cfg(target_os = "windows")]
+const DOWNLOAD_URL: &str = "https://downloads.getmonero.org/cli/monero-win-x64-v0.17.1.9.zip";
 
 const PACKED_FILE: &str = "monero-wallet-rpc";
```
Comment (thomaseizinger) [inline swap/src/monero/wallet_rpc.rs:32]: I think this might need a `cfg(not(target_os = "windows"))` otherwise you will be getting a "const already defined error".

File: swap/src/monero/wallet_rpc.rs [hunk 3]
```diff
@@ -163,11 +117,116 @@ impl WalletRpc {
...
+
+        remove_file(monero_wallet_rpc.archive_path()).await?;
+
+        Ok(())
+    }
+
+    #[cfg(target_os = "windows")]
+    async fn download(monero_wallet_rpc: &Self) -> Result<()> {
+        let mut options = OpenOptions::new();
+        {
```
Comment (thomaseizinger) [inline swap/src/monero/wallet_rpc.rs:192]: What is this block good for?

File: swap/src/monero/wallet_rpc.rs [hunk 4]
```diff
@@ -163,11 +117,116 @@ impl WalletRpc {
...
+        }
+
+        let file = std::fs::File::open(monero_wallet_rpc.archive_path())?;
+
+        let mut zip = zip::ZipArchive::new(file)?;
+
+        let name = zip
+            .file_names()
+            .find(|name| name.contains(PACKED_FILE))
+            .expect("zip archive contains monero wallet rpc")
```
Comment (thomaseizinger) [inline swap/src/monero/wallet_rpc.rs:221]: This will panic, should be `context`.

File: swap/src/monero/wallet_rpc.rs [hunk 5]
```diff
@@ -163,11 +117,116 @@ impl WalletRpc {
...
-    fn tar_path(&self) -> PathBuf {
+    fn archive_path(&self) -> PathBuf {
         self.working_dir.join("monero-cli-wallet.tar")
     }
 
     fn exec_path(&self) -> PathBuf {
         self.working_dir.join(PACKED_FILE)
     }
+
+    async fn download(monero_wallet_rpc: &Self) -> Result<()> {
```
Comment (thomaseizinger) [inline swap/src/monero/wallet_rpc.rs:128]: This will need a `cfg(not(windows))` as well.

File: swap/src/monero/wallet_rpc.rs [hunk 6]
```diff
@@ -163,11 +117,116 @@ impl WalletRpc {
...
+            .open(monero_wallet_rpc.archive_path())
+            .await?;
+
+        let byte_stream = reqwest::get(DOWNLOAD_URL)
+            .await?
+            .bytes_stream()
+            .map_err(|err| std::io::Error::new(ErrorKind::Other, err));
+
+        let mut stream = FramedRead::new(
+            BzDecoder::new(StreamReader::new(byte_stream)),
```
Comment (thomaseizinger) [inline swap/src/monero/wallet_rpc.rs:147]: This line is actually the only difference between the download of linux/macos and windows. I think we could make the part that is OS-specific a lot smaller here.

Happy to leave that to a follow-up though.

**Review by thomaseizinger — CHANGES_REQUESTED** [review]
Thank you!

Please extend CI to build on Windows as well to make sure it actually builds :)

I believe there are some missing cfg's still that will cause windows to fail at build-time.

File: swap/src/monero/wallet_rpc.rs (hunk 2 above)
Comment (rishflab) [reply swap/src/monero/wallet_rpc.rs:33]: Yep, I updated, moved it up before the constant declarations

File: swap/src/monero/wallet_rpc.rs [hunk 7]
```diff
@@ -211,9 +215,13 @@ impl WalletRpc {
             file.flush().await?;
         }
 
-        let file = std::fs::File::open(monero_wallet_rpc.archive_path())?;
+        let archive_path = monero_wallet_rpc.archive_path();
+        let unzip: JoinHandle<Result<ZipArchive<File>>> = tokio::spawn(async {
+            let file = File::open(archive_path)?;
+            Ok(ZipArchive::new(file)?)
```
Comment (thomaseizinger) [inline swap/src/monero/wallet_rpc.rs:222]: 1. That is not gonna do much, you will need to move all IO operations into the task.
2. You need to use `spawn_blocking` otherwise there is practically no difference to just doing it inline.

File: swap/src/monero/wallet_rpc.rs [hunk 8]
```diff
@@ -154,11 +118,126 @@ impl WalletRpc {
         })
     }
 
-    fn tar_path(&self) -> PathBuf {
+    fn archive_path(&self) -> PathBuf {
```
Comment (da-kami) [inline swap/src/monero/wallet_rpc.rs:121]: 🔧 I think this has to distinguish between windows and linux/mac as well - or are you specifying the `zip` will have a name ending in`tar`?

As far as I could see `archive_path` is used in both download functions.

File: swap/src/monero/wallet_rpc.rs (hunk 6 above)
Comment (da-kami) [reply swap/src/monero/wallet_rpc.rs:149]: Agreed! most of the `download` is duplicated. Follow-up OK for me as well.

**Review by da-kami — CHANGES_REQUESTED** [review]

File: swap/src/monero/wallet_rpc.rs [hunk 9]
```diff
@@ -226,7 +227,7 @@ impl WalletRpc {
         let name = zip
             .file_names()
             .find(|name| name.contains(PACKED_FILE))
-            .expect("zip archive contains monero wallet rpc")
+            .context("zip archive contains monero wallet rpc")?
```
Comment (thomaseizinger) [inline swap/src/monero/wallet_rpc.rs]: With having a `context` here, this message no longer makes sense. It should say why things went wrong: the zip archive **doesn't** contain the `monero-wallet-rpc` binary.

File: .github/workflows/ci.yml [hunk 10]
```diff
@@ -44,12 +44,14 @@ jobs:
...
       matrix:
-        target: [ x86_64-unknown-linux-gnu, x86_64-apple-darwin ]
+        target: [ x86_64-unknown-linux-gnu, x86_64-apple-darwin, x86_64-pc-windows-msvc ]
         include:
           - target: x86_64-unknown-linux-gnu
             os: ubuntu-latest
           - target: x86_64-apple-darwin
             os: macos-latest
+          - target: x86_64-pc-windows-msvc
+            os: windows-latest
```
Comment (thomaseizinger) [inline .github/workflows/ci.yml:54]: Please extend the bors configuration file to also listen for this task.

**Review by thomaseizinger — APPROVED** [review]
Sorry, missed the bors stuff in the earlier pass.

Otherwise good to go in from my side :)

File: swap/src/monero/wallet_rpc.rs (hunk 8 above)
Comment (rishflab) [reply swap/src/monero/wallet_rpc.rs:121]: I am specifying that the `zip` will have a name ending in `.tar`. I can rename it to `.archive` so that it is less confusing.

File: swap/src/monero/wallet_rpc.rs (hunk 6 above)
Comment (rishflab) [reply swap/src/monero/wallet_rpc.rs]: fixed it

File: swap/src/monero/wallet_rpc.rs [hunk 11]
```diff
@@ -92,48 +97,28 @@ impl WalletRpc {
...
             let mut stream = FramedRead::new(
-                BzDecoder::new(StreamReader::new(byte_stream)),
+                async_compression::tokio::bufread::BzDecoder::new(StreamReader::new(byte_stream)),
                 BytesCodec::new(),
             )
             .map_ok(|bytes| bytes.freeze());
 
+            #[cfg(target_os = "windows")]
+            let mut stream = FramedRead::new(StreamReader::new(byte_stream), BytesCodec::new())
+                .map_ok(|bytes| bytes.freeze());
```
Comment (thomaseizinger) [inline swap/src/monero/wallet_rpc.rs:109]: Nicely done!

**Review by thomaseizinger — APPROVED** [review]
Good work @rishflab !

Thanks for doing another iteration :)

**Comment by thomaseizinger** [comment]
The test failure seems to be what @da-kami fixed in #248, do we maybe need to rebase this PR so that these changes are included?

**Comment by thomaseizinger** [comment]
> The test failure seems to be what @da-kami fixed in #248, do we maybe need to rebase this PR so that these changes are included?

Ah well, #248 is not merged yet :sweat_smile: 

I bors'd it so hopefully those failures are a thing of the past now!

**Review by da-kami — APPROVED** [review]
