### PR TITLE
Always log at debug level to file

### LINKED ISSUE #278: Have a debug log file per swap and print its path to the user on startup
If stuff doesn't work for users, it would be good to have the logs even if they didn't pass `--debug`. We should configure tracing to always send the debug logs to a file.

The log file should probably be per swap.

Need to figure out how we can compose tracing subscribers because I think we can only set one.

### PR DESCRIPTION
**Pull request by rishflab**
WILL SQUASH DOWN TO 3 COMMITS WHEN APPROVED!

Log at debug level to file

EnvFilter is applied globally. This means you cannot log at INFO level 
to the terminal and at DEBUG level to log files. To get a around this 
limitation I had to implement the layer trait on a new type and filter 
in the on_event() trait method. Each swap has its own log file denoted 
by its swap_id. The logger appends to the existing file when resuming a 
swap.

Closes #278 

I think the `DebugTerminalPritner` and `InfoTerminalPrinter` could be consolidated with some effort with some generics wizardry. It works for now and I think it can be done later. I wish in general there was a cleaner way to do this.

### CODE REVIEW

File: swap/src/cli/trace.rs [hunk 1]
```diff
@@ -0,0 +1,147 @@
...
+
+pub fn init_tracing(
+    debug: bool,
+    dir: impl AsRef<Path>,
+    command: &Command,
+) -> Result<Option<WorkerGuard>> {
+    let is_terminal = atty::is(atty::Stream::Stderr);
+
+    let file_logger = |&swap_id| {
+        let appender = tracing_appender::rolling::never(dir, format!("{}.log", swap_id));
```
Comment (thomaseizinger) [inline swap/src/cli/trace.rs:23]: Nit:

```suggestion
        let appender = tracing_appender::rolling::never(dir, format!("swap-{}.log", swap_id));
```

File: swap/src/bin/swap.rs [hunk 2]
```diff
@@ -22,6 +22,7 @@ use std::time::Duration;
 use structopt::StructOpt;
 use swap::bitcoin::{Amount, TxLock};
 use swap::cli::command::{AliceMultiaddress, Arguments, Command, Data, MoneroParams};
+use swap::cli::trace::init_tracing;
```
Comment (thomaseizinger) [inline swap/src/bin/swap.rs:25]: Nit: Can we name the module `tracing` and the function `init` and call it as `tracing::init`?

File: swap/src/cli/trace.rs [hunk 3]
```diff
@@ -0,0 +1,147 @@
...
+                .with_ansi(is_terminal)
+                .with_target(false)
+                .with_writer(non_blocking),
+            guard,
+        )
+    };
+
+    match command {
+        Command::BuyXmr { .. } => {
+            let (file_logger, guard) = file_logger(&Uuid::new_v4());
```
Comment (thomaseizinger) [inline swap/src/cli/trace.rs:36]: You are generating a new swap ID here and not passing it to the outside! Hence it will be different from the actual swap ID!

File: swap/src/cli/trace.rs [hunk 4]
```diff
@@ -0,0 +1,147 @@
...
+pub fn init_tracing(
+    debug: bool,
+    dir: impl AsRef<Path>,
+    command: &Command,
+) -> Result<Option<WorkerGuard>> {
+    let is_terminal = atty::is(atty::Stream::Stderr);
+
+    let file_logger = |&swap_id| {
+        let appender = tracing_appender::rolling::never(dir, format!("{}.log", swap_id));
+        let (non_blocking, guard) = tracing_appender::non_blocking(appender);
```
Comment (thomaseizinger) [inline swap/src/cli/trace.rs:24]: Nit: I think ` appender` would be a better name than `non_blocking` because the latter sounds like it holds a boolean.

File: swap/src/cli/trace.rs [hunk 5]
```diff
@@ -0,0 +1,147 @@
...
+        (
+            fmt::layer()
+                .with_ansi(is_terminal)
+                .with_target(false)
+                .with_writer(non_blocking),
+            guard,
```
Comment (thomaseizinger) [inline swap/src/cli/trace.rs:30]: FYI: To avoid having to return this `guard`, you can also use `std::mem::forget`. Given that we are not a long-running deamon, this won't cause a harmful memory-leak as we will terminate eventually.

That should simplify some of the APIs.

File: swap/src/cli/trace.rs (hunk 3 above)
Comment (thomaseizinger) [reply swap/src/cli/trace.rs:36]: You will need to either return the `swap_id` from this whole function or pass it in from `main.rs`.

File: swap/src/cli/trace.rs [hunk 6]
```diff
@@ -0,0 +1,147 @@
...
+}
+
+pub struct InfoTerminalPrinter<S> {
+    pub fmt: tracing_subscriber::fmt::Layer<
+        S,
+        DefaultFields,
+        Format<tracing_subscriber::fmt::format::Full, ()>,
+        fn() -> std::io::Stdout,
+    >,
+}
```
Comment (thomaseizinger) [inline swap/src/cli/trace.rs:125]: All of these should be private to this module because I don't think they will be used outside of here.

Comment (thomaseizinger) [reply swap/src/cli/trace.rs:125]: Also applies to all fields.

It a good habit to always start with non-public structs and only make them public once the compiler complains.

File: swap/src/cli/trace.rs [hunk 7]
```diff
@@ -0,0 +1,147 @@
...
+
+pub struct DebugTerminalPrinter<S> {
+    pub fmt: tracing_subscriber::fmt::Layer<
+        S,
+        DefaultFields,
+        Format<tracing_subscriber::fmt::format::Full, ChronoLocal>,
+        fn() -> std::io::Stdout,
+    >,
+}
```
Comment (thomaseizinger) [inline swap/src/cli/trace.rs:116]: Usually, you have an easier time in Rust if you make a struct overly generic by saying:

```suggestion
pub struct DebugTerminalPrinter<L> {
    pub inner: L
}
```

And then only specify the trait bounds and/or generic parameters on `impl` blocks whenever necessary.

In this case, this might allow you to just have a generic `TerminalPrinter` with different constructors for different usecases because the difference in the type-signature (whether or not to print time) is outside of the struct definition.

File: swap/src/cli/trace.rs (hunk 6 above)
Comment (thomaseizinger) [reply swap/src/cli/trace.rs:125]: > All of these should be private to this module because I don't think they will be used outside of here.

I am not 100% certain but it might reveal that `TerminalPrinter` is dead code :grin:

**Review by thomaseizinger — COMMENTED** [review]
Thanks for digging into this! Very good findings!

The only thing that really needs addressing is the randomly generated `swap_id` within the `trace` module on `Command::XmrBtc`. All other comments are just ideas on how to simplify things a bit.

File: swap/src/bin/swap.rs (hunk 2 above)
Comment (thomaseizinger) [reply swap/src/bin/swap.rs:25]: If you do that, would be good to adjust for the `asb` as well!

File: swap/src/bin/swap.rs [hunk 8]
```diff
@@ -42,35 +42,11 @@ extern crate prettytable;
 async fn main() -> Result<()> {
     let args = Arguments::from_args();
 
-    let is_terminal = atty::is(atty::Stream::Stderr);
-    let base_subscriber = |level| {
-        FmtSubscriber::builder()
-            .with_writer(std::io::stderr)
-            .with_ansi(is_terminal)
-            .with_target(false)
-            .with_env_filter(format!("swap={}", level))
```
Comment (da-kami) [inline swap/src/bin/swap.rs:51]: Please use the `with_env_filter` for terminal printing in the new implementation as well! Otherwise the debug print for the terminal looks like this:

```
2021-04-06T10:49:22.293440+10:00 DEBUG Opening database at /Users/dakami/TEMP/swap/bob/01/database
2021-04-06T10:49:22.492383+10:00 DEBUG Reading in seed from /Users/dakami/TEMP/swap/bob/01/seed.pem
2021-04-06T10:49:28.264779+10:00 DEBUG Starting monero-wallet-rpc on port 50462
2021-04-06T10:49:30.040745+10:00 DEBUG connecting to 127.0.0.1:50462
2021-04-06T10:49:30.041971+10:00 DEBUG connected to 127.0.0.1:50462
2021-04-06T10:49:30.043520+10:00 DEBUG flushed 176 bytes
2021-04-06T10:49:30.044778+10:00 DEBUG parsed 5 headers
2021-04-06T10:49:30.044851+10:00 DEBUG incoming body is content-length (103 bytes)
2021-04-06T10:49:30.045013+10:00 DEBUG incoming body completed
2021-04-06T10:49:30.045431+10:00 DEBUG pooling idle connection for ("http", 127.0.0.1:50462)
2021-04-06T10:49:30.045627+10:00 DEBUG get_version RPC response: {
  "id": "1",
  "jsonrpc": "2.0",
  "result": {
    "release": true,
    "version": 65556
  }
}
2021-04-06T10:49:30.046670+10:00 DEBUG connecting to 127.0.0.1:50462
2021-04-06T10:49:30.046938+10:00 DEBUG connected to 127.0.0.1:50462
2021-04-06T10:49:30.047558+10:00 DEBUG flushed 228 bytes
2021-04-06T10:49:31.705720+10:00 DEBUG parsed 5 headers
2021-04-06T10:49:31.705808+10:00 DEBUG incoming body is content-length (59 bytes)
2021-04-06T10:49:31.705952+10:00 DEBUG incoming body completed
2021-04-06T10:49:31.706300+10:00 DEBUG pooling idle connection for ("http", 127.0.0.1:50462)
2021-04-06T10:49:31.706682+10:00 DEBUG open wallet RPC response: {
  "id": "1",
  "jsonrpc": "2.0",
  "result": {
  }
}
2021-04-06T10:49:31.706753+10:00 DEBUG Opened Monero wallet swap-tool-blockchain-monitoring-wallet
2021-04-06T10:49:31.706969+10:00 DEBUG reuse idle connection for ("http", 127.0.0.1:50462)
2021-04-06T10:49:31.709494+10:00 DEBUG flushed 193 bytes
2021-04-06T10:49:42.329512+10:00 DEBUG parsed 5 headers
2021-04-06T10:49:42.329637+10:00 DEBUG incoming body is content-length (403 bytes)
2021-04-06T10:49:42.329935+10:00 DEBUG incoming body completed
2021-04-06T10:49:42.330304+10:00 DEBUG pooling idle connection for ("http", 127.0.0.1:50462)
2021-04-06T10:49:42.330497+10:00 DEBUG get address RPC response: {
  "id": "1",
  "jsonrpc": "2.0",
  "result": {
    "address": "5BD7gmPTj6GchKqszYnAHTH3ZATujYLE63WDqoFQeLAw63CAhRG2U2QRq4sBhLjR4CfTnRDtxk7RFEeLia8VGMFNPWkuX6c",
    "addresses": [{
      "address": "5BD7gmPTj6GchKqszYnAHTH3ZATujYLE63WDqoFQeLAw63CAhRG2U2QRq4sBhLjR4CfTnRDtxk7RFEeLia8VGMFNPWkuX6c",
      "address_index": 0,
      "label": "Primary account",
      "used": false
    }]
  }
}
2021-04-06T10:49:42.335824+10:00 DEBUG Requesting quote
```

**Review by da-kami — CHANGES_REQUESTED** [review]

File: swap/src/bin/swap.rs (hunk 8 above)
Comment (da-kami) [reply swap/src/bin/swap.rs:51]: One more note: The logfile is actually not restriceted to `debug`, but contains `TRACE` level logs as well (Not exactly sure why at this point):

```
[2mApr 06 10:49:22.285[0m [34mDEBUG[0m Opening database at /Users/dakami/TEMP/swap/bob/01/database
[2mApr 06 10:49:22.492[0m [34mDEBUG[0m Reading in seed from /Users/dakami/TEMP/swap/bob/01/seed.pem
[2mApr 06 10:49:28.264[0m [34mDEBUG[0m Starting monero-wallet-rpc on port 50462
[2mApr 06 10:49:30.040[0m [35mTRACE[0m checkout waiting for idle connection: ("http", 127.0.0.1:50462)
[2mApr 06 10:49:30.040[0m [35mTRACE[0m Http::connect; scheme=Some("http"), host=Some("127.0.0.1"), port=Some(Port(50462))
[2mApr 06 10:49:30.040[0m [34mDEBUG[0m connecting to 127.0.0.1:50462
[2mApr 06 10:49:30.041[0m [34mDEBUG[0m connected to 127.0.0.1:50462
[2mApr 06 10:49:30.042[0m [35mTRACE[0m client handshake Http1
[2mApr 06 10:49:30.042[0m [35mTRACE[0m handshake complete, spawning background dispatcher task
[2mApr 06 10:49:30.042[0m [35mTRACE[0m flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Busy }
[2mApr 06 10:49:30.042[0m [35mTRACE[0m checkout dropped for ("http", 127.0.0.1:50462)
[2mApr 06 10:49:30.043[0m [35mTRACE[0m [1mencode_headers[0m: Client::encode method=POST, body=Some(Known(61))
[2mApr 06 10:49:30.043[0m [35mTRACE[0m sized write, len = 61
[2mApr 06 10:49:30.043[0m [34mDEBUG[0m flushed 176 bytes
[2mApr 06 10:49:30.043[0m [35mTRACE[0m flushed({role=client}): State { reading: Init, writing: KeepAlive, keep_alive: Busy }
[2mApr 06 10:49:30.044[0m [35mTRACE[0m Conn::read_head
[2mApr 06 10:49:30.044[0m [35mTRACE[0m [1mparse_headers[0m: Response.parse([Header; 100], [u8; 263])
[2mApr 06 10:49:30.044[0m [35mTRACE[0m [1mparse_headers[0m: Response.parse Complete(160)
[2mApr 06 10:49:30.044[0m [34mDEBUG[0m parsed 5 headers
[2mApr 06 10:49:30.044[0m [34mDEBUG[0m incoming body is content-length (103 bytes)
[2mApr 06 10:49:30.044[0m [35mTRACE[0m decode; state=Length(103)
[2mApr 06 10:49:30.044[0m [34mDEBUG[0m incoming body completed
[2mApr 06 10:49:30.045[0m [35mTRACE[0m maybe_notify; read_from_io blocked
[2mApr 06 10:49:30.045[0m [35mTRACE[0m flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
[2mApr 06 10:49:30.045[0m [35mTRACE[0m flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
[2mApr 06 10:49:30.045[0m [35mTRACE[0m put; add idle connection for ("http", 127.0.0.1:50462)
[2mApr 06 10:49:30.045[0m [34mDEBUG[0m pooling idle connection for ("http", 127.0.0.1:50462)
[2mApr 06 10:49:30.045[0m [34mDEBUG[0m get_version RPC response: {
  "id": "1",
  "jsonrpc": "2.0",
  "result": {
    "release": true,
    "version": 65556
  }
}
[2mApr 06 10:49:30.045[0m [35mTRACE[0m flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
[2mApr 06 10:49:30.045[0m [35mTRACE[0m pool closed, canceling idle interval
[2mApr 06 10:49:30.045[0m [35mTRACE[0m client tx closed
[2mApr 06 10:49:30.045[0m [35mTRACE[0m State::close_read()
[2mApr 06 10:49:30.046[0m [35mTRACE[0m State::close_write()
[2mApr 06 10:49:30.046[0m [35mTRACE[0m flushed({role=client}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
[2mApr 06 10:49:30.046[0m [35mTRACE[0m shut down IO complete
[2mApr 06 10:49:30.046[0m [35mTRACE[0m checkout waiting for idle connection: ("http", 127.0.0.1:50462)
[2mApr 06 10:49:30.046[0m [35mTRACE[0m Http::connect; scheme=Some("http"), host=Some("127.0.0.1"), port=Some(Port(50462))
[2mApr 06 10:49:30.046[0m [34mDEBUG[0m connecting to 127.0.0.1:50462
[2mApr 06 10:49:30.046[0m [34mDEBUG[0m connected to 127.0.0.1:50462
[2mApr 06 10:49:30.047[0m [35mTRACE[0m client handshake Http1
[2mApr 06 10:49:30.047[0m [35mTRACE[0m handshake complete, spawning background dispatcher task
[2mApr 06 10:49:30.047[0m [35mTRACE[0m flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Busy }
[2mApr 06 10:49:30.047[0m [35mTRACE[0m checkout dropped for ("http", 127.0.0.1:50462)
[2mApr 06 10:49:30.047[0m [35mTRACE[0m [1mencode_headers[0m: Client::encode method=POST, body=Some(Known(112))
[2mApr 06 10:49:30.047[0m [35mTRACE[0m sized write, len = 112
[2mApr 06 10:49:30.047[0m [34mDEBUG[0m flushed 228 bytes
[2mApr 06 10:49:30.047[0m [35mTRACE[0m flushed({role=client}): State { reading: Init, writing: KeepAlive, keep_alive: Busy }
[2mApr 06 10:49:31.705[0m [35mTRACE[0m Conn::read_head
[2mApr 06 10:49:31.705[0m [35mTRACE[0m [1mparse_headers[0m: Response.parse([Header; 100], [u8; 218])
[2mApr 06 10:49:31.705[0m [35mTRACE[0m [1mparse_headers[0m: Response.parse Complete(159)
[2mApr 06 10:49:31.705[0m [34mDEBUG[0m parsed 5 headers
[2mApr 06 10:49:31.705[0m [34mDEBUG[0m incoming body is content-length (59 bytes)
[2mApr 06 10:49:31.705[0m [35mTRACE[0m decode; state=Length(59)
[2mApr 06 10:49:31.705[0m [34mDEBUG[0m incoming body completed
[2mApr 06 10:49:31.706[0m [35mTRACE[0m maybe_notify; read_from_io blocked
[2mApr 06 10:49:31.706[0m [35mTRACE[0m flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
[2mApr 06 10:49:31.706[0m [35mTRACE[0m flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
[2mApr 06 10:49:31.706[0m [35mTRACE[0m put; add idle connection for ("http", 127.0.0.1:50462)
[2mApr 06 10:49:31.706[0m [34mDEBUG[0m pooling idle connection for ("http", 127.0.0.1:50462)
[2mApr 06 10:49:31.706[0m [34mDEBUG[0m open wallet RPC response: {
  "id": "1",
  "jsonrpc": "2.0",
  "result": {
  }
}
[2mApr 06 10:49:31.706[0m [34mDEBUG[0m Opened Monero wallet swap-tool-blockchain-monitoring-wallet
[2mApr 06 10:49:31.706[0m [35mTRACE[0m take? ("http", 127.0.0.1:50462): expiration = Some(90s)
[2mApr 06 10:49:31.706[0m [34mDEBUG[0m reuse idle connection for ("http", 127.0.0.1:50462)
[2mApr 06 10:49:31.709[0m [35mTRACE[0m [1mencode_headers[0m: Client::encode method=POST, body=Some(Known(78))
[2mApr 06 10:49:31.709[0m [35mTRACE[0m sized write, len = 78
[2mApr 06 10:49:31.709[0m [34mDEBUG[0m flushed 193 bytes
[2mApr 06 10:49:31.709[0m [35mTRACE[0m idle interval checking for expired
[2mApr 06 10:49:31.709[0m [35mTRACE[0m flushed({role=client}): State { reading: Init, writing: KeepAlive, keep_alive: Busy }
[2mApr 06 10:49:42.329[0m [35mTRACE[0m Conn::read_head
[2mApr 06 10:49:42.329[0m [35mTRACE[0m [1mparse_headers[0m: Response.parse([Header; 100], [u8; 563])
[2mApr 06 10:49:42.329[0m [35mTRACE[0m [1mparse_headers[0m: Response.parse Complete(160)
[2mApr 06 10:49:42.329[0m [34mDEBUG[0m parsed 5 headers
[2mApr 06 10:49:42.329[0m [34mDEBUG[0m incoming body is content-length (403 bytes)
[2mApr 06 10:49:42.329[0m [35mTRACE[0m decode; state=Length(403)
[2mApr 06 10:49:42.329[0m [34mDEBUG[0m incoming body completed
[2mApr 06 10:49:42.330[0m [35mTRACE[0m maybe_notify; read_from_io blocked
[2mApr 06 10:49:42.330[0m [35mTRACE[0m flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
[2mApr 06 10:49:42.330[0m [35mTRACE[0m flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
[2mApr 06 10:49:42.330[0m [35mTRACE[0m put; add idle connection for ("http", 127.0.0.1:50462)
[2mApr 06 10:49:42.330[0m [34mDEBUG[0m pooling idle connection for ("http", 127.0.0.1:50462)
[2mApr 06 10:49:42.330[0m [34mDEBUG[0m get address RPC response: {
  "id": "1",
  "jsonrpc": "2.0",
  "result": {
    "address": "5BD7gmPTj6GchKqszYnAHTH3ZATujYLE63WDqoFQeLAw63CAhRG2U2QRq4sBhLjR4CfTnRDtxk7RFEeLia8VGMFNPWkuX6c",
    "addresses": [{
      "address": "5BD7gmPTj6GchKqszYnAHTH3ZATujYLE63WDqoFQeLAw63CAhRG2U2QRq4sBhLjR4CfTnRDtxk7RFEeLia8VGMFNPWkuX6c",
      "address_index": 0,
      "label": "Primary account",
      "used": false
    }]
  }
}
[2mApr 06 10:49:42.330[0m [35mTRACE[0m flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
[2mApr 06 10:49:42.335[0m [34mDEBUG[0m Requesting quote
[2mApr 06 10:49:46.376[0m [33m WARN[0m Failed to dial Alice at /ip4/192.168.1.7/tcp/8765/p2p/12D3KooWPZ69DRp4wbGB3wJsxxsg1XW1EVZ2evtVwcARCF3a1nrx: Pending connection: Transport error: select error: Protocol error: I/O error: Broken pipe (os error 32)
[2mApr 06 10:49:46.377[0m [33m WARN[0m Communication error: protocol with peer 12D3KooWPZ69DRp4wbGB3wJsxxsg1XW1EVZ2evtVwcARCF3a1nrx failed due to DialFailure
[2mApr 06 10:49:46.384[0m [35mTRACE[0m client tx closed
[2mApr 06 10:49:46.385[0m [35mTRACE[0m State::close_read()
[2mApr 06 10:49:46.385[0m [35mTRACE[0m State::close_write()
[2mApr 06 10:49:46.385[0m [35mTRACE[0m pool closed, canceling idle interval
[2mApr 06 10:49:46.385[0m [35mTRACE[0m flushed({role=client}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
```

Comment (rishflab) [reply swap/src/bin/swap.rs:51]: oh dear this doesn't look good

Comment (thomaseizinger) [reply swap/src/bin/swap.rs:51]: Need to make sure to disable ANSI for the logfile!

Comment (rishflab) [reply swap/src/bin/swap.rs:51]: fixed!

File: swap/src/cli/trace.rs [hunk 9]
```diff
@@ -9,56 +9,70 @@ use tracing_subscriber::fmt::format::{DefaultFields, Format};
...
 use tracing_subscriber::registry::LookupSpan;
-use tracing_subscriber::{fmt, Layer, Registry};
+use tracing_subscriber::{fmt, EnvFilter, Layer, Registry};
 use uuid::Uuid;
 
 pub fn init_tracing(
     debug: bool,
     dir: impl AsRef<Path>,
     command: &Command,
+    new_swap_id: &Uuid,
```
Comment (thomaseizinger) [inline swap/src/cli/trace.rs]: This is kind of confusing IMO because the `new_swap_id` is only used if the command is `XmrBtc`. Can we clean this up so that we are not passing redundant arguments?

**Review by thomaseizinger — CHANGES_REQUESTED** [review]
Thanks for working in the comments!

One more thing I'd like to discuss :)

Also, feel free to squash things together already, the diff isn't too big to review in its entirety.

File: swap/src/cli/trace.rs (hunk 9 above)
Comment (rishflab) [reply swap/src/cli/trace.rs]: Hmmm I don't like this either :( but I think it is bit more involved than a clean up.
We could add `swap_id` to `Command::BuyXmr`. Need to figure out how to get structopt to ignore it when parsing args

**Review by thomaseizinger — APPROVED** [review]
